package org.example.db.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import org.example.db.Dao;
import org.example.shop.Product;

public class HsqlProductDao implements Dao<Product>{

	
	private Statement stmt;
	private PreparedStatement insert;
	private PreparedStatement delete;
	private PreparedStatement update;
	private PreparedStatement getById;
	private PreparedStatement getAll;
	
	
	public HsqlProductDao(Connection connection)
	{
		
		try {
			
			stmt = connection.createStatement();
			
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			
			boolean exists = false;
			while(rs.next())
			{
				if("product".equalsIgnoreCase(rs.getString("TABLE_NAME")))
				{
					exists = true;
					break;
				}
			}
			
			insert = connection.prepareStatement(""
					+ "INSERT INTO product(name,description,prize)"
					+ " VALUES(?,?,?)");
			
			getById = connection.prepareStatement(""
					+ "SELECT * FROM product WHERE id=?");
			
			if(!exists)
			{
				stmt.executeUpdate(""
						+ "CREATE TABLE product("
						+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
						+ "name varchar(50),"
						+ "description varchar(500),"
						+ "prize double,"
						+ ")");
				
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}
	
	public void save(Product ent) {
		
		try {
			insert.setString(1, ent.getName());
			insert.setString(2, ent.getDescription());
			insert.setDouble(3, ent.getPrize());
			insert.executeUpdate();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	public void delete(Product ent) {
		// TODO Auto-generated method stub
		
	}

	public List<Product> getAll() {
		// TODO Auto-generated method stub
		return null;
	}

	public Product get(int id) {
		Product p = null;
		try {
			getById.setInt(1, id);
			ResultSet rs = getById.executeQuery();
			while(rs.next())
			{
				p = new Product();
				p.setId(rs.getInt("id"));
				p.setDescription(rs.getString("description"));
				p.setPrize(rs.getDouble("prize"));
				p.setName(rs.getString("name"));
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		return p;
	}

	public void update(Product ent) {
		// TODO Auto-generated method stub
		
	}

	
	
}
